<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\GroceryManager.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pantry\GroceryManager.Modules.Pantry.csproj" />
    <ProjectReference Include="..\..\src\Modules\ShoppingPresets\GroceryManager.Modules.ShoppingPresets.csproj" />
    <ProjectReference Include="..\..\src\Modules\Stocktakes\GroceryManager.Modules.Stocktakes.csproj" />
    <ProjectReference Include="..\..\src\Modules\Shopping\GroceryManager.Modules.Shopping.csproj" />
    <ProjectReference Include="..\..\src\Modules\InventoryHistory\GroceryManager.Modules.InventoryHistory.csproj" />
  </ItemGroup>

</Project>