"use client"

import { useEffect, useState } from "react"
import { useRouter, useSearchParams } from "next/navigation"

import { getApiErrorMessage } from "@/lib/api/get-api-error-message"
import type { ShoppingPresetResponse, StocktakeResponse } from "@/lib/api/generated/models"
import { postApiShoppingLists } from "@/lib/api/generated/shopping-lists/shopping-lists"
import { getApiShoppingPresets } from "@/lib/api/generated/shopping-presets/shopping-presets"
import { getApiStocktakes } from "@/lib/api/generated/stocktakes/stocktakes"
import { Button } from "@/shared/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card"
import { Input } from "@/shared/components/ui/input"
import { Label } from "@/shared/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/shared/components/ui/radio-group"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select"
import { Spinner } from "@/shared/components/ui/spinner"
import { useErrorToast } from "@/shared/hooks/use-error-toast"

export function ShoppingListGenerator() {
  const router = useRouter(); const search = useSearchParams(); const selectedStocktake = search.get("stocktakeId") ?? ""; const [presets, setPresets] = useState<ShoppingPresetResponse[]>([]); const [stocktakes, setStocktakes] = useState<StocktakeResponse[]>([]); const [source, setSource] = useState<"pantry" | "stocktake">(selectedStocktake ? "stocktake" : "pantry"); const [presetId, setPresetId] = useState(""); const [stocktakeId, setStocktakeId] = useState(selectedStocktake); const [name, setName] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>()
  useErrorToast(error, "Shopping list not created")
  useEffect(() => { Promise.all([getApiShoppingPresets(), getApiStocktakes({ page: 1, pageSize: 50 })]).then(([loadedPresets, loadedStocktakes]) => { setPresets(loadedPresets.filter((preset) => !preset.isArchived)); setStocktakes(loadedStocktakes.items.filter((stocktake) => stocktake.status === 1)); }).catch((loadError) => setError(getApiErrorMessage(loadError, "Unable to load list sources."))).finally(() => setLoading(false)) }, [])
  const availableStocktakes = stocktakes.filter((stocktake) => !presetId || stocktake.shoppingPresetId === presetId)
  async function generate() { if (source === "stocktake" && !stocktakeId) { setError("Choose a completed stocktake."); return } if (source === "stocktake" && presetId && !availableStocktakes.some((stocktake) => stocktake.id === stocktakeId)) { setError("Choose a stocktake completed with the selected preset."); return } setSaving(true); try { const list = await postApiShoppingLists({ shoppingPresetId: presetId || null, stocktakeId: source === "stocktake" ? stocktakeId : null, name: name.trim() || null }); router.replace(`/app/shopping-lists/${list.id}/review`) } catch (generateError) { setError(getApiErrorMessage(generateError, "Unable to generate shopping list.")); setSaving(false) } }
  if (loading) return <div className="flex min-h-64 items-center justify-center"><Spinner className="size-6" /></div>
  return <div className="mx-auto max-w-2xl space-y-6"><header><h1 className="text-2xl font-semibold">New shopping list</h1><p className="mt-1 text-sm text-muted-foreground">Choose the pantry snapshot that should shape this list.</p></header><Card><CardHeader><CardTitle>List source</CardTitle><CardDescription>Use current pantry stock, or make a list from a completed stocktake.</CardDescription></CardHeader><CardContent className="space-y-5"><RadioGroup value={source} onValueChange={(value) => setSource(value as "pantry" | "stocktake")}><label className="flex cursor-pointer items-start gap-3 rounded-lg border p-3"><RadioGroupItem value="pantry" className="mt-0.5" /><span><span className="font-medium">Current pantry</span><span className="mt-0.5 block text-sm text-muted-foreground">Calculate against the stock in your pantry now.</span></span></label><label className="mt-2 flex cursor-pointer items-start gap-3 rounded-lg border p-3"><RadioGroupItem value="stocktake" className="mt-0.5" /><span><span className="font-medium">Completed stocktake</span><span className="mt-0.5 block text-sm text-muted-foreground">Use the quantities confirmed in a past stocktake.</span></span></label></RadioGroup>{source === "stocktake" && <div className="space-y-2"><Label>Completed stocktake</Label><Select value={stocktakeId} onValueChange={setStocktakeId}><SelectTrigger className="w-full"><SelectValue placeholder="Select a stocktake" /></SelectTrigger><SelectContent>{availableStocktakes.map((stocktake) => <SelectItem key={stocktake.id} value={stocktake.id}>{new Date(stocktake.completedAtUtc ?? stocktake.startedAtUtc).toLocaleDateString()} · {stocktake.entries.length} entries</SelectItem>)}</SelectContent></Select></div>}<div className="space-y-2"><Label>Preset <span className="text-muted-foreground">(optional)</span></Label><Select value={presetId || "none"} onValueChange={(value) => setPresetId(value === "none" ? "" : value)}><SelectTrigger className="w-full"><SelectValue placeholder="No preset" /></SelectTrigger><SelectContent><SelectItem value="none">No preset</SelectItem>{presets.map((preset) => <SelectItem key={preset.id} value={preset.id}>{preset.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="list-name">List name <span className="text-muted-foreground">(optional)</span></Label><Input id="list-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Weekly groceries" /></div><div className="flex justify-end"><Button onClick={() => void generate()} disabled={saving}>{saving && <Spinner />}{saving ? "Generating…" : "Generate list"}</Button></div></CardContent></Card></div>
}
