"use client"

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { useParams, useRouter } from "next/navigation"
import { CheckIcon, RotateCcwIcon, XIcon } from "lucide-react"
import { toast } from "sonner"

import { getApiErrorMessage } from "@/lib/api/get-api-error-message"
import type { ShoppingListItemResponse, ShoppingListResponse } from "@/lib/api/generated/models"
import { getApiShoppingListsListId, postApiShoppingListsListIdComplete, postApiShoppingListsListIdItemsItemIdUndoPurchase, putApiShoppingListsListIdItemsItemId } from "@/lib/api/generated/shopping-lists/shopping-lists"
import { Badge } from "@/shared/components/ui/badge"
import { Button } from "@/shared/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card"
import { Input } from "@/shared/components/ui/input"
import { Spinner } from "@/shared/components/ui/spinner"
import { useErrorToast } from "@/shared/hooks/use-error-toast"

export function ShoppingListShop() {
  const { listId } = useParams<{ listId: string }>(); const router = useRouter(); const [list, setList] = useState<ShoppingListResponse>(); const [quantities, setQuantities] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [savingId, setSavingId] = useState<string>(); const [completing, setCompleting] = useState(false); const [error, setError] = useState<string>()
  useErrorToast(error, "Shopping list not updated")
  async function load() { try { const loaded = await getApiShoppingListsListId(listId); setList(loaded); setQuantities((current) => Object.fromEntries(loaded.items.map((item) => [item.id, current[item.id] ?? String(item.actualPurchaseQuantity ?? item.suggestedPurchaseQuantity ?? "")]))) } catch (loadError) { setError(getApiErrorMessage(loadError, "Unable to load shopping list.")) } finally { setLoading(false) } }
  useEffect(() => { getApiShoppingListsListId(listId).then((loaded) => { setList(loaded); setQuantities(Object.fromEntries(loaded.items.map((item) => [item.id, String(item.actualPurchaseQuantity ?? item.suggestedPurchaseQuantity ?? "")]))) }).catch((loadError) => setError(getApiErrorMessage(loadError, "Unable to load shopping list."))).finally(() => setLoading(false)) }, [listId])
  const pending = useMemo(() => list?.items.filter((item) => item.outcome === 0) ?? [], [list]); const resolved = list?.items.filter((item) => item.outcome !== 0) ?? []
  async function purchase(item: ShoppingListItemResponse) { const quantity = Number(quantities[item.id]); if (!Number.isFinite(quantity) || quantity <= 0) { setError("Enter a quantity greater than zero before marking an item purchased."); return } setSavingId(item.id); try { const outcome = quantity === Number(item.suggestedPurchaseQuantity) ? 1 : 2; await putApiShoppingListsListIdItemsItemId(listId, item.id, { suggestedPurchaseQuantity: item.suggestedPurchaseQuantity, actualPurchaseQuantity: quantity, outcome, destinationLocationId: item.destinationLocationId, version: item.version }); await load(); toast.success(`${item.itemName} purchased`, { action: { label: "Undo", onClick: () => void undo(item.id) } }); } catch (purchaseError) { setError(getApiErrorMessage(purchaseError, "Unable to record purchase.")) } finally { setSavingId(undefined) } }
  async function notPurchased(item: ShoppingListItemResponse) { setSavingId(item.id); try { await putApiShoppingListsListIdItemsItemId(listId, item.id, { suggestedPurchaseQuantity: item.suggestedPurchaseQuantity, actualPurchaseQuantity: 0, outcome: 3, destinationLocationId: item.destinationLocationId, version: item.version }); await load(); toast.message(`${item.itemName} not purchased`); } catch (updateError) { setError(getApiErrorMessage(updateError, "Unable to update item.")) } finally { setSavingId(undefined) } }
  async function undo(itemId: string) { try { await postApiShoppingListsListIdItemsItemIdUndoPurchase(listId, itemId); await load(); toast.success("Purchase undone") } catch (undoError) { setError(getApiErrorMessage(undoError, "Unable to undo purchase.")) } }
  async function complete() { if (pending.length) return; setCompleting(true); try { await postApiShoppingListsListIdComplete(listId); toast.success("Shopping list completed"); router.replace(`/app/shopping-lists/${listId}`) } catch (completeError) { setError(getApiErrorMessage(completeError, "Unable to complete shopping list.")); setCompleting(false) } }
  if (loading) return <div className="flex min-h-64 items-center justify-center"><Spinner className="size-6" /></div>
  if (!list) return <div className="py-12 text-center text-sm text-muted-foreground">Shopping list unavailable.</div>
  return <div className="mx-auto max-w-2xl space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">{list.name}</h1><p className="mt-1 text-sm text-muted-foreground">Tap purchased to apply that quantity to Pantry immediately.</p></div><Button variant="outline" size="sm" asChild><Link href={`/app/shopping-lists/${list.id}/review`}>Review</Link></Button></header><div className="flex items-center justify-between rounded-lg bg-surface-muted px-4 py-3 text-sm"><span>{resolved.length} of {list.items.length} resolved</span><Badge>{pending.length ? `${pending.length} left` : "Ready to finish"}</Badge></div><section className="space-y-2">{pending.map((item) => <Card key={item.id} className="gap-3 py-4"><CardContent className="space-y-3"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{item.itemName}</p><p className="text-sm text-muted-foreground">Suggested {item.suggestedPurchaseQuantity ?? 0} {item.trackingUnit ?? ""}</p></div>{item.isOnAnotherActiveList && <Badge variant="outline">Also on another list</Badge>}</div><div className="flex items-center gap-2"><Input aria-label={`${item.itemName} purchase quantity`} className="w-28" type="number" min="0.001" step="0.001" value={quantities[item.id] ?? ""} onChange={(event) => setQuantities((current) => ({ ...current, [item.id]: event.target.value }))} /><span className="text-sm text-muted-foreground">{item.trackingUnit ?? ""}</span></div><div className="flex flex-wrap gap-2"><Button size="sm" disabled={savingId === item.id} onClick={() => void purchase(item)}><CheckIcon />Purchased</Button><Button size="sm" variant="outline" disabled={savingId === item.id} onClick={() => void notPurchased(item)}><XIcon />Not purchased</Button></div></CardContent></Card>)}</section>{resolved.length > 0 && <section className="space-y-2"><h2 className="text-sm font-medium text-muted-foreground">Resolved</h2>{resolved.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span>{item.itemName} · {item.outcome === 3 ? "Not purchased" : `${item.actualPurchaseQuantity} purchased`}</span>{item.inventoryAppliedAtUtc && <Button size="xs" variant="ghost" onClick={() => void undo(item.id)}><RotateCcwIcon />Undo</Button>}</div>)}</section>}<Card><CardHeader><CardTitle>Finish shopping</CardTitle><CardDescription>{pending.length ? "Resolve every item before completing this list." : "Completing keeps this list in your shopping history."}</CardDescription></CardHeader><CardContent><Button disabled={pending.length > 0 || completing} onClick={() => void complete()}>{completing && <Spinner />}{completing ? "Completing…" : "Complete shopping list"}</Button></CardContent></Card></div>
}
