// <auto-generated />
using System;
using GroceryManager.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroceryManager.Api.Migrations
{
    [DbContext(typeof(GroceryManagerDbContext))]
    partial class GroceryManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroceryManager.Api.Entities.Entitlements.Entitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Entitlements", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Entitlements.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Entitlements.PlanEntitlement", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntitlementId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LimitValue")
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("PlanId", "EntitlementId");

                    b.HasIndex("EntitlementId");

                    b.ToTable("PlanEntitlements", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanEntitlements_LimitValue", "\"LimitValue\" IS NULL OR \"LimitValue\" >= 0");
                        });
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.InventoryHistory.InventoryAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PantryItemLocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityDelta")
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid?>("ReversesAdjustmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceShoppingListItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceStocktakeEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("ReversesAdjustmentId")
                        .IsUnique();

                    b.HasIndex("SourceShoppingListItemId")
                        .IsUnique()
                        .HasFilter("\"SourceShoppingListItemId\" IS NOT NULL");

                    b.HasIndex("SourceStocktakeEntryId")
                        .IsUnique()
                        .HasFilter("\"SourceStocktakeEntryId\" IS NOT NULL");

                    b.HasIndex("PantryItemLocationId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("InventoryAdjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryAdjustments_NotSelfReversing", "\"ReversesAdjustmentId\" IS NULL OR \"ReversesAdjustmentId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("citext");

                    b.Property<Guid>("PantryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PantryId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = FALSE");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.ItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultCategoryKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DefaultTrackingUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.Pantry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("Pantries", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.PantryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("BufferDays")
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConsumptionPeriodDays")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("ConsumptionQuantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultStorageLocationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("citext");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("PackageSize")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("PackageUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PantryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferredProduct")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SourceTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackingUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DefaultStorageLocationId");

                    b.HasIndex("SourceTemplateId");

                    b.HasIndex("PantryId", "CategoryId", "Name")
                        .HasFilter("\"IsArchived\" = FALSE");

                    b.ToTable("PantryItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_PantryItems_Consumption", "(\"ConsumptionQuantity\" IS NULL OR \"ConsumptionQuantity\" >= 0) AND (\"ConsumptionPeriodDays\" IS NULL OR \"ConsumptionPeriodDays\" > 0) AND \"BufferDays\" >= 0");

                            t.HasCheckConstraint("CK_PantryItems_ConsumptionPair", "(\"ConsumptionQuantity\" IS NULL) = (\"ConsumptionPeriodDays\" IS NULL)");

                            t.HasCheckConstraint("CK_PantryItems_PackageSize", "\"PackageSize\" IS NULL OR \"PackageSize\" >= 0");
                        });
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.PantryItemLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset?>("LastConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PantryItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PantryItemId", "StorageLocationId")
                        .IsUnique();

                    b.HasIndex("StorageLocationId", "SortOrder");

                    b.ToTable("PantryItemLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_PantryItemLocations_CurrentQuantity", "\"CurrentQuantity\" >= 0");
                        });
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("citext");

                    b.Property<Guid>("PantryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PantryId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsArchived\" = FALSE");

                    b.HasIndex("PantryId", "SortOrder");

                    b.ToTable("StorageLocations", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Shopping.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("PantryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourcePresetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceStocktakeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("StockChangedSinceGeneration")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("SourcePresetId");

                    b.HasIndex("SourceStocktakeId")
                        .IsUnique()
                        .HasFilter("\"SourceStocktakeId\" IS NOT NULL");

                    b.HasIndex("PantryId", "Status");

                    b.ToTable("ShoppingLists", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Shopping.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualPurchaseQuantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("BrandSnapshot")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CategoryNameSnapshot")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("InventoryAppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("PackageSizeSnapshot")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("PackageUnitSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PantryItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RequiredAtGeneration")
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StockAtGeneration")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("SuggestedPurchaseQuantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("TrackingUnitSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("ShoppingListId");

                    b.HasIndex("PantryItemId", "Outcome");

                    b.ToTable("ShoppingListItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShoppingListItems_Quantities", "(\"PackageSizeSnapshot\" IS NULL OR \"PackageSizeSnapshot\" >= 0) AND (\"StockAtGeneration\" IS NULL OR \"StockAtGeneration\" >= 0) AND (\"RequiredAtGeneration\" IS NULL OR \"RequiredAtGeneration\" >= 0) AND (\"SuggestedPurchaseQuantity\" IS NULL OR \"SuggestedPurchaseQuantity\" >= 0) AND (\"ActualPurchaseQuantity\" IS NULL OR \"ActualPurchaseQuantity\" >= 0)");
                        });
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.ShoppingPresets.PresetCategory", b =>
                {
                    b.Property<Guid>("ShoppingPresetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ShoppingPresetId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PresetCategories", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.ShoppingPresets.PresetItemRule", b =>
                {
                    b.Property<Guid>("ShoppingPresetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PantryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("ShoppingPresetId", "PantryItemId");

                    b.HasIndex("PantryItemId");

                    b.ToTable("PresetItemRules", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.ShoppingPresets.ShoppingPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CoverageDays")
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEverythingPreset")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PantryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PantryId")
                        .HasFilter("\"IsArchived\" = FALSE");

                    b.ToTable("ShoppingPresets", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShoppingPresets_CoverageDays", "\"CoverageDays\" >= 0");
                        });
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Stocktakes.Stocktake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PantryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShoppingPresetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingPresetId");

                    b.HasIndex("PantryId", "StartedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("Stocktakes", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Stocktakes.StocktakeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedQuantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<bool>("IsOutlier")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("ItemSortOrderSnapshot")
                        .HasColumnType("integer");

                    b.Property<string>("LocationNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("LocationSortOrderSnapshot")
                        .HasColumnType("integer");

                    b.Property<Guid>("PantryItemLocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PreviousConfirmedQuantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("RecordedQuantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("StocktakeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackingUnitSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PantryItemLocationId");

                    b.HasIndex("StocktakeId", "PantryItemLocationId")
                        .IsUnique();

                    b.ToTable("StocktakeEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_StocktakeEntries_Quantities", "\"PreviousConfirmedQuantity\" >= 0 AND \"EstimatedQuantity\" >= 0 AND (\"RecordedQuantity\" IS NULL OR \"RecordedQuantity\" >= 0)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Entitlements.PlanEntitlement", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Entitlements.Entitlement", null)
                        .WithMany()
                        .HasForeignKey("EntitlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.Entitlements.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.InventoryHistory.InventoryAdjustment", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.Pantry.PantryItemLocation", null)
                        .WithMany()
                        .HasForeignKey("PantryItemLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.InventoryHistory.InventoryAdjustment", null)
                        .WithOne()
                        .HasForeignKey("GroceryManager.Api.Entities.InventoryHistory.InventoryAdjustment", "ReversesAdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroceryManager.Api.Entities.Shopping.ShoppingListItem", null)
                        .WithOne()
                        .HasForeignKey("GroceryManager.Api.Entities.InventoryHistory.InventoryAdjustment", "SourceShoppingListItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroceryManager.Api.Entities.Stocktakes.StocktakeEntry", null)
                        .WithOne()
                        .HasForeignKey("GroceryManager.Api.Entities.InventoryHistory.InventoryAdjustment", "SourceStocktakeEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.Category", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.Pantry", null)
                        .WithMany()
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.Pantry", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("GroceryManager.Api.Entities.Pantry.Pantry", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.PantryItem", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.Pantry.StorageLocation", null)
                        .WithMany()
                        .HasForeignKey("DefaultStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroceryManager.Api.Entities.Pantry.Pantry", null)
                        .WithMany()
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.Pantry.ItemTemplate", null)
                        .WithMany()
                        .HasForeignKey("SourceTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.PantryItemLocation", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.PantryItem", null)
                        .WithMany()
                        .HasForeignKey("PantryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.Pantry.StorageLocation", null)
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Pantry.StorageLocation", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.Pantry", null)
                        .WithMany()
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Shopping.ShoppingList", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.Pantry", null)
                        .WithMany()
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.ShoppingPresets.ShoppingPreset", null)
                        .WithMany()
                        .HasForeignKey("SourcePresetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroceryManager.Api.Entities.Stocktakes.Stocktake", null)
                        .WithOne()
                        .HasForeignKey("GroceryManager.Api.Entities.Shopping.ShoppingList", "SourceStocktakeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Shopping.ShoppingListItem", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.StorageLocation", null)
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroceryManager.Api.Entities.Pantry.PantryItem", null)
                        .WithMany()
                        .HasForeignKey("PantryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroceryManager.Api.Entities.Shopping.ShoppingList", null)
                        .WithMany()
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.ShoppingPresets.PresetCategory", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.ShoppingPresets.ShoppingPreset", null)
                        .WithMany()
                        .HasForeignKey("ShoppingPresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.ShoppingPresets.PresetItemRule", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.PantryItem", null)
                        .WithMany()
                        .HasForeignKey("PantryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.ShoppingPresets.ShoppingPreset", null)
                        .WithMany()
                        .HasForeignKey("ShoppingPresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.ShoppingPresets.ShoppingPreset", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.Pantry", null)
                        .WithMany()
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Stocktakes.Stocktake", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.Pantry", null)
                        .WithMany()
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.ShoppingPresets.ShoppingPreset", null)
                        .WithMany()
                        .HasForeignKey("ShoppingPresetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GroceryManager.Api.Entities.Stocktakes.StocktakeEntry", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Pantry.PantryItemLocation", null)
                        .WithMany()
                        .HasForeignKey("PantryItemLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.Stocktakes.Stocktake", null)
                        .WithMany()
                        .HasForeignKey("StocktakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryManager.Api.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GroceryManager.Api.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
