"use client"

import { useEffect, useState, type FormEvent } from "react"
import { useRouter } from "next/navigation"
import { InfoIcon } from "lucide-react"
import { getApiCategories } from "@/lib/api/generated/categories/categories"
import { getApiStorageLocations } from "@/lib/api/generated/storage-locations/storage-locations"
import type { CategoryResponse, StorageLocationResponse } from "@/lib/api/generated/models"
import { postApiPantryItems } from "@/lib/api/generated/pantry-items/pantry-items"
import { getApiErrorMessage } from "@/lib/api/get-api-error-message"
import { Button } from "@/shared/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card"
import { Checkbox } from "@/shared/components/ui/checkbox"
import { Field, FieldGroup, FieldLabel } from "@/shared/components/ui/field"
import { Input } from "@/shared/components/ui/input"
import { Spinner } from "@/shared/components/ui/spinner"
import { showErrorToast, showSuccessToast, useErrorToast } from "@/shared/hooks/use-error-toast"

export function NewPantryItemForm() {
  const router = useRouter(); const [categories, setCategories] = useState<CategoryResponse[]>([]); const [areas, setAreas] = useState<StorageLocationResponse[]>([]); const [selectedAreas, setSelectedAreas] = useState<string[]>([]); const [error, setError] = useState<string>(); const [submitting, setSubmitting] = useState(false)
  useErrorToast(error, "Item not saved")
  useEffect(() => { Promise.all([getApiCategories(), getApiStorageLocations()]).then(([categoryRows, areaRows]) => { const activeAreas = areaRows.filter((area) => !area.isArchived); setCategories(categoryRows.filter((category) => !category.isArchived)); setAreas(activeAreas); setSelectedAreas(activeAreas[0] ? [activeAreas[0].id] : []) }).catch((value) => setError(getApiErrorMessage(value, "Unable to load item options."))) }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const quantity = Number(data.get("consumptionQuantity")); const days = Number(data.get("consumptionPeriodDays")); if (!Number.isFinite(quantity) || quantity <= 0 || !Number.isFinite(days) || days <= 0) { showErrorToast("Tell us how much you use and how often.", "Item not saved"); return } if (!categories[0] || !selectedAreas.length) { showErrorToast("Choose at least one stock area.", "Item not saved"); return } setSubmitting(true); try { const item = await postApiPantryItems({ categoryId: categories[0].id, sourceTemplateId: null, defaultStorageLocationId: selectedAreas[0], name: String(data.get("name")), icon: null, brand: null, preferredProduct: null, notes: null, trackingUnit: 0, packageSize: null, packageUnit: null, consumptionQuantity: quantity, consumptionPeriodDays: days, bufferDays: Number(data.get("bufferDays") || 0), locations: selectedAreas.map((storageLocationId, index) => ({ storageLocationId, currentQuantity: 0, sortOrder: index })) }); showSuccessToast("Regular item added"); router.replace(`/app/pantry/items/${item.id}`) } catch (value) { setError(getApiErrorMessage(value, "Unable to create item.")); setSubmitting(false) } }
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Add regular item</h1><p className="mt-1 text-sm text-muted-foreground">Add only what the next shopping list needs.</p></header><Card><CardHeader><CardTitle>Shopping details</CardTitle><CardDescription>You will count what you have during your next stocktake.</CardDescription></CardHeader><CardContent><form className="space-y-6" onSubmit={submit}><FieldGroup className="grid gap-5 md:grid-cols-2"><Field className="md:col-span-2"><FieldLabel htmlFor="name">Name</FieldLabel><Input id="name" name="name" maxLength={160} required placeholder="e.g. Bananas" /></Field><Field className="md:col-span-2"><FieldLabel>Stock areas</FieldLabel><div className="grid gap-2 sm:grid-cols-3">{areas.map((area) => <label key={area.id} className="flex cursor-pointer items-center gap-2 rounded-[18px] bg-surface-muted px-4 py-3 shadow-xs transition-[background-color,box-shadow,transform] hover:-translate-y-0.5 hover:bg-accent hover:shadow-sm"> <Checkbox checked={selectedAreas.includes(area.id)} onCheckedChange={(checked) => setSelectedAreas((current) => checked ? [...current, area.id] : current.filter((id) => id !== area.id))} />{area.name}</label>)}</div></Field><Field><FieldLabel htmlFor="consumptionQuantity">We use</FieldLabel><Input id="consumptionQuantity" name="consumptionQuantity" type="number" min="0.001" step="0.001" placeholder="e.g. 6" required /></Field><Field><FieldLabel htmlFor="consumptionPeriodDays">Every how many days?</FieldLabel><Input id="consumptionPeriodDays" name="consumptionPeriodDays" type="number" min="1" step="1" placeholder="e.g. 7" required /></Field><Field><div className="flex items-center gap-1.5"><FieldLabel htmlFor="bufferDays">Extra to keep on hand</FieldLabel><InfoIcon className="size-4 text-muted-foreground" title="Additional quantity to keep after covering normal use." /></div><Input id="bufferDays" name="bufferDays" type="number" min="0" step="0.5" defaultValue="0" /></Field></FieldGroup><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => router.back()}>Cancel</Button><Button type="submit" disabled={submitting}>{submitting && <Spinner />}{submitting ? "Saving…" : "Add item"}</Button></div></form></CardContent></Card></div>
}
